1. Catching the IllegalArgumentException thrown by WALA when we try to find the immediate post-dominator on the CFG generated for java.lang.Finalizer$FinalizerThread. This exception is thrown because this method has an early return followed by an infinite loop. Because of this, there is no path from the infinite loop body to the exit node. 2. Catching NoClassDefFoundError every time we try to look up all DeclaredMethods of a class 3. Ignore the if expression of basic blocks with only one successor when summarizing a method